version: '3.7'
services:
    ubuntu:
        container_name: dg_server
        build:
            context: images/ubuntu
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./html:/var/www/html
            - ./images/ubuntu/conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./images/ubuntu/conf/php.ini:/etc/php/8.1/fpm/php.ini
        ports:
            - "80:80"
            - "443:443"
    db:
      container_name: dg_db
      build:
        context: images/mysql_ko
        dockerfile: Dockerfile
      restart: always
      environment:
          MYSQL_DATABASE: dg
          MYSQL_USER: dg
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
      volumes:
          - ./db_data:/var/lib/mysql    
      ports:
          - "3306:3306"
